export const CREATE_PATIENT = 'CREATE_PATIENT';
export const EDIT_PATIENT = 'EDIT_PATIENT';
export const FETCH_PATIENTS = 'FETCH_PATIENTS';
export const FETCH_PATIENT = 'FETCH_PATIENT';
export const DELETE_PATIENT = 'DELETE_PATIENT';

export const CREATE_APPOINTMENT = 'CREATE_APPOINTMENT';
export const EDIT_APPOINTMENT = 'EDIT_APPOINTMENT';
export const FETCH_APPOINTMENTS = 'FETCH_APPOINTMENTS';
export const FETCH_APPOINTMENT = 'FETCH_APPOINTMENT';
export const DELETE_APPOINTMENT = 'DELETE_APPOINTMENT';
export const FETCH_APPOINTMENTS_BY_PATIENT = 'FETCH_APPOINTMENTS_BY_PATIENT';


export const FETCH_APPOINTMENT_TYPES = 'FETCH_APPOINTMENT_TYPE';

export const AUTHENTICATION_LOGIN = 'AUTHENTICATION_LOGIN';
export const AUTHENTICATION_LOGOUT = 'AUTHENTICATION_LOGOUT';


export const ADD_ERROR = 'ADD_ERROR';
export const REMOVE_ERROR = 'REMOVE_ERROR';
export const RESET_ERROR_MESSAGE = 'RESET_ERROR_MESSAGE';
